# Generated by Django 5.1.5 on 2025-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('arena', 'Playing Arena'), ('gym', 'Gym'), ('farmhouse', 'Farm House'), ('saloon', 'Saloon'), ('hotel', 'Hotel Room'), ('pool', 'Swimming Pool'), ('cafe', 'Cafe'), ('event', 'Event Space'), ('shop', 'Shop')], max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('timing', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
