# Generated by Django 5.1.5 on 2025-05-12 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Playing Arena', 'Playing Arena'), ('Gym', 'Gym'), ('Farm House', 'Farm House'), ('Hotel Room', 'Hotel Room'), ('Saloon', 'Saloon'), ('Swimming Pool', 'Swimming Pool'), ('Cafe', 'Cafe'), ('Event Space', 'Event Space'), ('House', 'House'), ('Shop', 'Shop')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='ads/images/')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('bank', models.CharField(choices=[('meezan', 'Meezan Bank'), ('sadapay', 'SadaPay'), ('bank_alfalah', 'Bank Alfalah'), ('faysal', 'Faysal Bank'), ('hbl', 'Habib Bank Limited'), ('mcb', 'MCB Bank Limited'), ('ubl', 'United Bank Limited'), ('nbp', 'National Bank of Pakistan'), ('js_bank', 'JS Bank'), ('bank_of_punjab', 'Bank of Punjab'), ('standard_chartered', 'Standard Chartered Bank'), ('albaraka', 'Al Baraka Bank'), ('askari', 'Askari Bank'), ('bank_islamic', 'Bank Islami Pakistan Limited')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.spot')),
            ],
        ),
    ]
