# Generated by Django 5.1.5 on 2025-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Playing Arena', 'Playing Arena'), ('Gym', 'Gym'), ('Farm House', 'Farm House'), ('Saloon', 'Saloon'), ('Hotel Room', 'Hotel Room'), ('Swimming Pool', 'Swimming Pool'), ('Cafe', 'Cafe'), ('Event Space', 'Event Space'), ('Shop', 'Shop'), ('House', 'House')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='ads/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
